### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by greenrd** [noelmarkham/lambdadays-2015#2]
After I fixed the build issue (see #1 ) I got this error on slide 4:

scala> r
java.util.concurrent.TimeoutException: Futures timed out after [1 second]
  at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
  at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116)
  at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
  at scala.concurrent.Await$.result(package.scala:116)
  ... 67 elided

Maybe the timeout needs to be increased.

**Comment by noelmarkham** [comment]
Again, this works for me. Did you run the code on the previous slides?

**Comment by greenrd** [comment]
Yes, I did, but my network connection is bad so maybe it takes longer than 1 second to contact Twitter?

**Comment by noelmarkham** [comment]
It doesn't actually go to twitter - I wouldn't take that risk during a live talk - https://github.com/noelmarkham/scaladays-2015/blob/master/src/main/scala/com/noelmarkham/scaladays/external/Twitter.scala#L24
